import { BannerItem, BusinessSettings } from '@/src/types/index.ts';

/**
 * Primary bundled hero banner asset guaranteed to exist in /public/images/
 */
export const BUNDLED_HERO_BANNER = '/images/hero_banner_full.jpg';

/**
 * Sequenced fallback list of locally bundled images
 */
export const LOCAL_BANNER_FALLBACKS: readonly string[] = [
  '/images/hero_banner_full.jpg',
  '/images/ankita_banner.jpg',
  '/images/ankita_banner.png',
  '/images/user_banner.jpg',
  '/images/user_banner.png',
  '/images/uploaded_hero_banner.png',
] as const;

/**
 * Validates and normalizes an image URL string.
 * Accepts:
 * - Local relative paths starting with '/' (e.g. /images/...)
 * - Valid HTTPS or HTTP URLs (e.g. Firebase Storage, Unsplash, CDN)
 * - Safe compressed Base64 data URLs (data:image/...)
 * 
 * Rejects:
 * - Null, undefined, empty or whitespace-only strings
 * - Browser session-only blob: URLs (which break upon refresh or across devices)
 * - Non-string or malformed inputs
 */
export function normalizeBannerUrl(url: unknown): string | null {
  if (typeof url !== 'string') return null;

  const trimmed = url.trim();
  if (!trimmed) return null;

  // Reject temporary session blob URLs immediately
  if (trimmed.startsWith('blob:')) {
    console.warn('[BannerValidator] Rejected temporary session blob URL:', trimmed);
    return null;
  }

  // Reject 'undefined', 'null', or placeholder strings
  const lower = trimmed.toLowerCase();
  if (lower === 'undefined' || lower === 'null' || lower === '[object object]' || lower === '') {
    return null;
  }

  // Allow safe base64 data URLs (generated by client-side compression)
  if (trimmed.startsWith('data:image/')) {
    return trimmed;
  }

  // Allow local bundled assets starting with / or ./
  if (trimmed.startsWith('/') || trimmed.startsWith('./')) {
    return trimmed;
  }

  // Handle absolute web URLs
  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
      return trimmed;
    }
  } catch {
    // Malformed URL string
    return null;
  }

  return null;
}

/**
 * Checks whether an image URL is valid and persistent.
 */
export function isValidBannerUrl(url: unknown): boolean {
  return normalizeBannerUrl(url) !== null;
}

/**
 * Inspects a banner list and returns the first valid active banner URL,
 * or the first valid banner if no active banner is flagged.
 */
export function getActiveBannerFromList(bannerList?: BannerItem[] | null): string | null {
  if (!bannerList || !Array.isArray(bannerList) || bannerList.length === 0) {
    return null;
  }

  // 1. Look for explicitly active valid banner
  for (const item of bannerList) {
    if (item && item.active) {
      const valid = normalizeBannerUrl(item.imageUrl);
      if (valid) return valid;
    }
  }

  // 2. Fallback to first valid banner in the list
  for (const item of bannerList) {
    if (item) {
      const valid = normalizeBannerUrl(item.imageUrl);
      if (valid) return valid;
    }
  }

  return null;
}

/**
 * Resolves the primary banner URL following the strict priority system:
 * Priority 1: Valid active banner URL from businessSettings.bannerUrl
 * Priority 2: Valid active banner from businessSettings.bannerList
 * Priority 3: Local bundled image /images/hero_banner_full.jpg
 * Priority 4: First available local banner fallback
 */
export function resolveBannerUrl(settings?: Partial<BusinessSettings> | null): string {
  if (!settings) {
    return BUNDLED_HERO_BANNER;
  }

  // Priority 1: settings.bannerUrl
  const p1 = normalizeBannerUrl(settings.bannerUrl);
  if (p1) return p1;

  // Priority 2: active banner in bannerList
  const p2 = getActiveBannerFromList(settings.bannerList);
  if (p2) return p2;

  // Priority 3 & 4: Bundled local image
  return BUNDLED_HERO_BANNER;
}

/**
 * Safely merges Firestore remote settings into default/cached business settings.
 * Ensures the app never crashes from missing fields, and never overwrites valid
 * defaults with undefined or empty values.
 */
export function safeMergeBusinessSettings(
  defaults: BusinessSettings,
  remote?: Partial<BusinessSettings> | null
): BusinessSettings {
  if (!remote || typeof remote !== 'object') {
    return defaults;
  }

  const resolvedBanner =
    normalizeBannerUrl(remote.bannerUrl) ||
    getActiveBannerFromList(remote.bannerList) ||
    defaults.bannerUrl ||
    BUNDLED_HERO_BANNER;

  const resolvedArtistPhoto =
    normalizeBannerUrl(remote.artistPhoto) ||
    defaults.artistPhoto ||
    BUNDLED_HERO_BANNER;

  // Clean banner list
  const cleanBannerList: BannerItem[] = Array.isArray(remote.bannerList)
    ? remote.bannerList
        .filter((b) => b && typeof b === 'object' && normalizeBannerUrl(b.imageUrl) !== null)
        .map((b) => ({
          id: b.id || `banner-${Date.now()}`,
          title: b.title || 'Studio Banner',
          subtitle: b.subtitle || '',
          imageUrl: normalizeBannerUrl(b.imageUrl)!,
          link: b.link || '',
          active: Boolean(b.active),
        }))
    : defaults.bannerList || [];

  return {
    ...defaults,
    ...remote,
    // Guarantee crucial string fields are never empty/undefined
    businessName: remote.businessName?.trim() || defaults.businessName,
    artistName: remote.artistName?.trim() || defaults.artistName,
    ownerName: remote.ownerName?.trim() || defaults.ownerName,
    phone: remote.phone?.trim() || defaults.phone,
    whatsapp: remote.whatsapp?.trim() || defaults.whatsapp,
    email: remote.email?.trim() || defaults.email,
    adminEmail: remote.adminEmail?.trim() || defaults.adminEmail,
    authorizedAdminEmails:
      Array.isArray(remote.authorizedAdminEmails) && remote.authorizedAdminEmails.length > 0
        ? remote.authorizedAdminEmails
        : defaults.authorizedAdminEmails,
    bannerUrl: resolvedBanner,
    artistPhoto: resolvedArtistPhoto,
    bannerList: cleanBannerList.length > 0 ? cleanBannerList : defaults.bannerList,
    bannerTitle: remote.bannerTitle?.trim() || defaults.bannerTitle,
    bannerSubtitle: remote.bannerSubtitle?.trim() || defaults.bannerSubtitle,
    bannerSlogan: remote.bannerSlogan?.trim() || defaults.bannerSlogan,
    bannerTagline: remote.bannerTagline?.trim() || defaults.bannerTagline,
    bannerRightBadge: remote.bannerRightBadge?.trim() || defaults.bannerRightBadge,
    bannerRightQuote: remote.bannerRightQuote?.trim() || defaults.bannerRightQuote,
    bannerTrust1: remote.bannerTrust1?.trim() || defaults.bannerTrust1,
    bannerTrust2: remote.bannerTrust2?.trim() || defaults.bannerTrust2,
    bannerTrust3: remote.bannerTrust3?.trim() || defaults.bannerTrust3,
  };
}
